### ISSUE TITLE
Image Processing and Storage

### ISSUE THREAD

**Issue by jpappel** [cs399f24/BingoMaker#11]
In order to efficiently store tiles with images, we should resize them on upload. The implementation should receive data either as a stream or read from somewhere in memory. The processed file should be able to be stored locally to disk and to the cloud via an object storage solutions (AWS S3 for this project).

**Comment by yousufkanan** [comment]
what is the desired dimensions for the resize

**Comment by drekdrek** [comment]
i think this is going to have to wait until we decide on the size of the bingo card UI

**Comment by jpappel** [comment]
The resized dimensions shouldn't be a blocker for this at all. In my mind it makes sense to have a function `resize_image(fp, dimensions: tuple[int, int]) -> Image` and a function/method `save_image(image: Image, image_details: dict, driver: StorageDriver) -> None` to handle image saving.

For image processing I recommended the [Pillow](https://pypi.org/project/pillow/) library. The official documentation [has an example of thumbnail creation](https://pillow.readthedocs.io/en/stable/reference/Image.html#create-thumbnails) which is the essentially the purpose of this issue.

I want to clarify that any code for this **should not** contain any web technology, it should operate with python file-like or path-like objects.
