### ISSUE TITLE
Data Persistence

### ISSUE THREAD

**Issue by jpappel** [cs399f24/BingoMaker#2]
Data should be persistent across application starts and stops. The data will be both textual (bingo tile text, user name) and binary (tile images). Ideally it multiple drivers will be supported. At least one local and one cloud driver must be implemented.

I've provided some potential options below for each.

## Textual Data Storage Options

* Cloud: DynamoDB
* [Local: DynamoDB](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html)
* Cloud: AmazonRDS
* Local: File System Based

## Binary Data Storage Options

* Cloud: S3
* Local: File System

**Comment by drekdrek** [comment]
DynamoDB was finished in #24
